name: Build Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Show Files
        run: ls -la

      - name: Build Docker Image
        run: |
          docker build -t dk:latest .
